"""add date

Revision ID: 685c1ca21762
Revises: 804d493f8b15
Create Date: 2026-04-26 18:21:15.710348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '685c1ca21762'
down_revision: Union[str, Sequence[str], None] = '804d493f8b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookedslot', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookedslot', 'date')
    # ### end Alembic commands ###
