"""add short name

Revision ID: 9666c6f66d21
Revises: 78681f99d34f
Create Date: 2026-05-01 08:31:33.256229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9666c6f66d21'
down_revision: Union[str, Sequence[str], None] = '78681f99d34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_hospital_short_name'), 'hospital', ['short_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospital_short_name'), table_name='hospital')
    op.drop_column('hospital', 'short_name')
    # ### end Alembic commands ###
